language: go

go:
  - "1.4"
  - "1.3"
  - "1.2"
  - "1.1"

sudo: false

install:
  - echo nothing to install

script:
  - set -o pipefail
  - go test -v ./... | sed ''/FAIL/s//$(printf "\033[31mFAIL\033[0m")/''
  - gem install social_snippet
  - sspm install ./
  - diff <(echo '// @snip <contest.go:main.go>' | ssnip | grep -v @snippet) <(cd src; cat main.go | ssnip | grep -v @snippet)

cache:
  directories:
    - $HOME/gopath

